#!/usr/bin/env python
# -*- coding: ISO-8859-1 -*-
#
# generated by wxGlade 0.6.8 on Sat Sep 13 20:58:01 2014
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class BasicFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: BasicFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.frame_1_statusbar = self.CreateStatusBar(1, 0)
        self.bitmap_1 = wx.StaticBitmap(self, wx.ID_ANY, wx.Bitmap("forumbanner.gif", wx.BITMAP_TYPE_ANY))
        self.label_3 = wx.StaticText(self, wx.ID_ANY, _("Aquaforum login naam"), style=wx.ALIGN_RIGHT)
        self.loginNaam = wx.TextCtrl(self, wx.ID_ANY, "")
        self.buttonSelectFile = wx.Button(self, wx.ID_ANY, _("Selecteer bestand"))
        self.text_ctrl_Filepath = wx.TextCtrl(self, wx.ID_ANY, "")
        self.radio_box_3 = wx.RadioBox(self, wx.ID_ANY, _("Dimensies"), choices=[_("800x600(standaard, groot)"), _("640x480 (middelgroot)"), _("320x240 (klein)"), _("160x120(heel klein, handig voor avatar)")], majorDimension=4, style=wx.RA_SPECIFY_ROWS)
        self.button_VoorbeeldGrootte = wx.Button(self, wx.ID_ANY, _("Voorbeeld grootte"))
        self.buttonUpload = wx.Button(self, wx.ID_ANY, _("Upload bestand naar forum"))
        self.label_4 = wx.StaticText(self, wx.ID_ANY, _("Als je deze knop gebruikt dan converteert het programma het plaatje naar de juiste afmetingen \nen plaatst het programma het plaatje op aquaforum. \nDit kan enige tijd duren! Zie de statusbalk onderaan voor informatie.\n\n-  Riba"))
        self.button_archief = wx.Button(self, wx.ID_ANY, _("Archief van de plaatjes"))
        self.button_5 = wx.Button(self, wx.ID_ANY, _("button_5"))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: BasicFrame.__set_properties
        self.SetTitle(_("Aquaforum upload programma"))
        _icon = wx.EmptyIcon()
        _icon.CopyFromBitmap(wx.Bitmap("icon.ico", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.SetSize((742, 667))
        self.SetBackgroundColour(wx.Colour(0, 127, 255))
        self.frame_1_statusbar.SetStatusWidths([-1])
        # statusbar fields
        frame_1_statusbar_fields = [_("Aquaforum file upload programma")]
        for i in range(len(frame_1_statusbar_fields)):
            self.frame_1_statusbar.SetStatusText(frame_1_statusbar_fields[i], i)
        self.label_3.SetBackgroundColour(wx.Colour(0, 127, 255))
        self.text_ctrl_Filepath.SetMinSize((400, 21))
        self.radio_box_3.SetBackgroundColour(wx.Colour(0, 127, 255))
        self.radio_box_3.SetSelection(0)
        self.label_4.SetBackgroundColour(wx.Colour(0, 127, 255))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: BasicFrame.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.GridSizer(3, 5, 0, 0)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8.Add(self.bitmap_1, 0, wx.FIXED_MINSIZE, 0)
        sizer_8.Add((20, 20), 0, wx.EXPAND | wx.FIXED_MINSIZE, 0)
        sizer_2.Add(sizer_8, 1, wx.EXPAND, 0)
        sizer_3.Add(self.label_3, 0, wx.ALIGN_CENTER_VERTICAL | wx.FIXED_MINSIZE, 0)
        sizer_3.Add((20, 20), 0, wx.FIXED_MINSIZE, 0)
        sizer_3.Add(self.loginNaam, 0, wx.ALIGN_CENTER_VERTICAL | wx.FIXED_MINSIZE, 0)
        sizer_2.Add(sizer_3, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_4.Add(self.buttonSelectFile, 0, wx.ALIGN_CENTER_VERTICAL | wx.FIXED_MINSIZE, 0)
        sizer_4.Add(self.text_ctrl_Filepath, 0, wx.ALIGN_CENTER_VERTICAL | wx.FIXED_MINSIZE, 0)
        sizer_2.Add(sizer_4, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_1.Add(self.radio_box_3, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_1.Add((20, 20), 0, wx.FIXED_MINSIZE, 0)
        sizer_1.Add(self.button_VoorbeeldGrootte, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_2.Add(sizer_1, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_7.Add(self.buttonUpload, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_7.Add((20, 20), 0, wx.FIXED_MINSIZE, 0)
        sizer_7.Add(self.label_4, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_2.Add(sizer_7, 1, wx.EXPAND, 0)
        sizer_2.Add(self.button_archief, 0, wx.FIXED_MINSIZE, 3)
        grid_sizer_1.Add(self.button_5, 0, 0, 0)
        sizer_2.Add(grid_sizer_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_2)
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class BasicFrame

class MyDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_1 = wx.StaticText(self, wx.ID_ANY, _("Het bericht is geplaatst op aquaforum. Je kan de volgende code gebruiken in je bericht:"))
        self.text_ctrl_Code = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_READONLY | wx.TE_LINEWRAP)
        self.button_1 = wx.Button(self, wx.ID_ANY, _("Zet de code in het klembord (clipboard)"))
        self.label_2 = wx.StaticText(self, wx.ID_ANY, _("Als je op de knop \"Zet de code in het klembord (clipboard)\" drukt, dan kan je vervolgens naar het aquaforum surfen met je browser. \nMaak een bericht waar je het plaatje in wilt hebben, klik rechts met de muis in het bericht  en kies \"plakken\" (of \"paste\"). \nDan staat de code in het bericht."))
        self.button_2 = wx.Button(self, wx.ID_ANY, _("Klaar"))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyDialog.__set_properties
        self.SetTitle(_("Bericht"))
        _icon = wx.EmptyIcon()
        _icon.CopyFromBitmap(wx.Bitmap("icon.ico", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.SetBackgroundColour(wx.Colour(0, 127, 255))
        self.label_1.SetBackgroundColour(wx.Colour(0, 127, 255))
        self.text_ctrl_Code.SetMinSize((400, 127))
        self.label_2.SetBackgroundColour(wx.Colour(0, 127, 255))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyDialog.__do_layout
        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_5.Add(self.label_1, 0, wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL | wx.FIXED_MINSIZE, 0)
        sizer_6.Add(self.text_ctrl_Code, 0, wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL | wx.FIXED_MINSIZE, 0)
        sizer_6.Add(self.button_1, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_5.Add(sizer_6, 1, wx.EXPAND, 0)
        sizer_5.Add(self.label_2, 0, wx.FIXED_MINSIZE, 0)
        sizer_5.Add(self.button_2, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL | wx.FIXED_MINSIZE, 0)
        self.SetSizer(sizer_5)
        sizer_5.Fit(self)
        self.Layout()
        # end wxGlade

# end of class MyDialog
if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frmMain = BasicFrame(None, wx.ID_ANY, "")
    app.SetTopWindow(frmMain)
    frmMain.Show()
    app.MainLoop()