#!/usr/bin/env python
# -*- coding: ISO-8859-1 -*-
# generated by wxGlade 0.3.5.1 on Fri Sep 02 14:39:13 2005

import wx
import os
import imp
import sys

def main_is_frozen():
   return (hasattr(sys, "frozen") or # new py2exe
           hasattr(sys, "importers") # old py2exe
           or imp.is_frozen("__main__")) # tools/freeze

def get_main_dir():
   if main_is_frozen():
       return os.path.dirname(sys.executable)
   return os.path.dirname(sys.argv[0])

class DrawingArea(wx.Window):
    def __init__(self, parent, id):
        sty = wx.NO_BORDER
        wx.Window.__init__( self, parent, id, style=sty )
        self.parent = parent
        self.SetBackgroundColour( wx.WHITE )
        self.SetCursor( wx.CROSS_CURSOR )

        # Some initalisation, just to reminds the user that a variable
        # called self.BufferBmp exists. See self.OnSize().
        self.BufferBmp = None

        #EVT_SIZE(self, self.OnSize)
        wx.EVT_PAINT(self, self.OnPaint)
        #self.Bind(wx.EVT_PAINT, self.OnPaint)
        self.path = None #path to picture

         
    def OnPaint(self,event):
        
        dc = wx.ClientDC( self )
        dc.BeginDrawing()
        image = None
        if self.path<>None:
            image = wx.Image( self.path, wx.BITMAP_TYPE_JPEG )
        else:
            image = wx.Image( os.path.join(get_main_dir(), "test.jpg"), wx.BITMAP_TYPE_JPEG )            
            #image.LoadFile()
            #bitmap = wx.Bitmap(image,-1)
        bitmap = wx.BitmapFromImage( image, depth=-1 )
        dc.DrawBitmap( bitmap, 0, 0 )
        dc.EndDrawing()


    def setPath(self, path):
        self.path = path
        self.Refresh()                 
        


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.window_1 = DrawingArea(self, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("Example")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        self.sizer_1 = wx.BoxSizer(wx.VERTICAL)
        self.sizer_1.Add(self.window_1, 1, wx.EXPAND, 0)
        self.SetAutoLayout(True)
        self.SetSizer(self.sizer_1)
        self.sizer_1.Fit(self)
        self.sizer_1.SetSizeHints(self)
        self.Layout()
        # end wxGlade

    def setPath(self, path):
        if path<>None and path<>() and path<>"":
            self.window_1.setPath(path)
# end of class MyFrame


